"use client";

import { useState } from "react";
import { reviewLectures } from "./fixtures";

export function ImportReview({onClose}:{onClose():void}) {
  const [rows,setRows]=useState(reviewLectures.slice(0,3).map((l,i)=>({...l,week:i===2?"":l.week})));
  const [done,setDone]=useState(false);
  const [batch,setBatch]=useState("");
  const ready=rows.length>0&&rows.every(r=>r.title.trim()&&r.course.trim()&&r.week&&r.instructor.trim());
  function update(id:string, key:"title"|"course"|"week"|"instructor",value:string){setRows(items=>items.map(r=>r.id===id?{...r,[key]:value}:r));}
  return <section className="ux-import"><header className="ux-app-nav"><h1>Review</h1><button className="ux-push" onClick={onClose}>Close</button></header>{done?<div className="ux-import-complete"><h2>Review complete</h2><p>Sample batch only. No lectures were uploaded.</p><button onClick={()=>setDone(false)}>Back to review</button></div>:<><div className="ux-import-content"><div className="ux-filter-row"><span>{rows.length} lectures</span><select aria-label="Set week for all imports" value={batch} onChange={e=>{setBatch(e.target.value);if(e.target.value)setRows(items=>items.map(r=>({...r,week:e.target.value})));}}><option value="">Set week for all</option><option value="2">Week 2</option><option value="3">Week 3</option><option value="4">Week 4</option></select><button className="ux-push" aria-label="Add sample PDF" onClick={()=>{const l=reviewLectures[rows.length%reviewLectures.length];setRows(items=>[...items,{...l,id:crypto.randomUUID(),week:batch}]);}}>Upload ↑</button></div><div className="ux-import-table" role="table" aria-label="Review sample lectures"><div className="ux-import-head" role="row">{["Lecture","Course","Week","Instructor",""].map((s,i)=><span role="columnheader" key={i}>{s}</span>)}</div>{rows.map(r=><div className="ux-import-row" role="row" key={r.id}><div role="cell"><input aria-label={`Title for ${r.id}`} value={r.title} aria-invalid={!r.title.trim()} onChange={e=>update(r.id,"title",e.target.value)}/></div><div role="cell"><input aria-label={`Course for ${r.id}`} value={r.course} aria-invalid={!r.course.trim()} onChange={e=>update(r.id,"course",e.target.value)}/></div><div role="cell"><select aria-label={`Week for ${r.id}`} value={r.week} aria-invalid={!r.week} onChange={e=>update(r.id,"week",e.target.value)}><option value="">Week</option>{[1,2,3,4,5,6].map(w=><option key={w} value={w}>Week {w}</option>)}</select></div><div role="cell"><input list="ux-instructors" aria-label={`Instructor for ${r.id}`} aria-invalid={!r.instructor.trim()} value={r.instructor} onChange={e=>update(r.id,"instructor",e.target.value)}/></div><div role="cell"><button aria-label={`Remove sample ${r.title}`} onClick={()=>setRows(items=>items.filter(row=>row.id!==r.id))}>×</button></div></div>)}</div>{!rows.length&&<p className="ux-empty">No files. Use Upload to add a sample.</p>}<datalist id="ux-instructors">{["Mitsouras","Huwe","Vansal","Rinaldi"].map(i=><option key={i}>{i}</option>)}</datalist></div><footer className="ux-import-footer"><button onClick={onClose}>Cancel</button><button className="ux-primary" disabled={!ready} onClick={()=>setDone(true)}>Finalize</button></footer></>}</section>;
}
