import type { Lecture } from "./lecture-store";

export const seedLectures: Lecture[] = [
  {
    id: "dna-tech",
    title: "DNA Technology and its Applications",
    lecturer: "Katherine Mitsouras, PhD",
    week: 2,
    course: "Medical & Clinical Foundations",
    academicYear: "2026-2027",
    favorite: false,
    pages: 57,
    slos: [
      "Describe genetic linkage analysis, its use in identifying disease genes, and its limitations.",
      "Describe how whole-genome and whole-exome sequencing identify genes for monogenic disease.",
      "Select WES or linkage analysis for an appropriate clinical scenario.",
      "Compare molecular diagnostic techniques used in genetic testing.",
      "Describe Northern blotting and gene-expression microarrays.",
      "Explain basic gene-therapy approaches and DNA-delivery methods.",
      "Describe drawbacks of gene-therapy approaches.",
      "Explain genome editing and CRISPR/Cas treatment of monogenic disease.",
    ],
    outline: ["Identifying the genetic basis of disease", "Diagnostic testing and screening", "Gene expression methods", "DNA methods for treatment", "Genome editing with CRISPR/Cas"],
    summary: "Methods for identifying disease genes, diagnosing monogenic disorders, measuring gene expression, and treating genetic disease through gene therapy and genome editing.",
    notes: {},
    markups: {},
    markedSlides: [],
    flaggedSLOs: [],
    slides: [
      { page: 7, heading: "Disease gene identification", text: "Linkage analysis maps a region containing a disease gene; whole-genome and exome sequencing identify causative genes and mutations." },
      { page: 16, heading: "Whole Exome Sequencing", text: "WES captures and sequences exons, which comprise about 2% of the genome and contain many disease-causing mutations." },
      { page: 39, heading: "Diagnostic testing methods", text: "PCR, PCR-RFLP, ARMS-PCR, ASO hybridization, Southern blotting and Sanger sequencing differ by whether the mutation is known and by mutation type." },
      { page: 49, heading: "CRISPR/Cas", text: "CRISPR-associated proteins and guide RNA enable targeted genome editing; repair can introduce a desired DNA sequence." },
    ],
    createdAt: "2026-08-10T08:00:00.000Z",
  },
  {
    id: "intro-cytogenetics",
    title: "Introduction to Cytogenetics",
    lecturer: "Katherine Mitsouras, PhD",
    week: 1,
    course: "Medical & Clinical Foundations",
    academicYear: "2026-2027",
    favorite: false,
    pages: 40,
    slos: [
      "Explain the uses and limitations of G-banded karyotype, FISH, and array CGH.",
      "Describe structural chromosome variation and how it causes disease.",
      "Describe mechanisms underlying changes in chromosome ploidy and the association with maternal age.",
      "Define reciprocal and Robertsonian translocations and familial trisomy 21.",
      "Explain clinical manifestations in offspring of balanced-translocation carriers.",
      "Describe the three viable autosomal trisomies and prenatal measurement of nuchal translucency.",
      "Select an appropriate laboratory method for a cytogenetic abnormality.",
    ],
    outline: ["Chromosome morphology and ISCN nomenclature", "Methods for chromosome analysis", "Numerical chromosome abnormalities", "Structural chromosome abnormalities", "Clinical syndromes and laboratory selection"],
    summary: "Chromosome morphology and nomenclature, cytogenetic testing methods, numerical abnormalities, structural rearrangements, and associated clinical syndromes.",
    notes: {},
    markups: {},
    markedSlides: [],
    flaggedSLOs: [],
    slides: [
      { page: 8, heading: "Chromosome nomenclature", text: "ISCN positions use chromosome number, p or q arm, region, band and sub-band." },
      { page: 18, heading: "Comparison of chromosome analysis", text: "Chromosome banding, FISH and array CGH differ in resolution and ability to detect balanced rearrangements or DNA copy-number changes." },
      { page: 21, heading: "Changes in ploidy", text: "Meiotic nondisjunction produces disomic and nullisomic gametes and occurs more frequently with advanced maternal age." },
      { page: 29, heading: "Translocations", text: "Reciprocal translocations exchange material between chromosomes. Robertsonian translocations fuse two acrocentric chromosomes." },
    ],
    createdAt: "2026-08-03T08:00:00.000Z",
  },
];
